# 11 · Worker–route opportunity cost
## Keep the allocator fixed. Improve the alternatives it sees.

**One bounded research milestone:** replay 69 saved states, then run at most one activated primary endpoint pair and one no-change control. Preserve notebook 10's final-sale gate in both arms.

This notebook does not reinstall packages, redownload data, modify GitHub or cloud resources, or run new complete seasons. Candidate scores are conditional route representations—not calibrated cash forecasts. Stop at an error and bundle the diagnostics.

In [1]:
from pathlib import Path
import json, sys, subprocess, time, os, signal, select
import pandas as pd
import plotly.io as pio
from IPython.display import display
BASE = Path.cwd()
if not (BASE / 'run_routes.py').is_file():
    BASE = Path.home() / 'kaggriculture_route_opportunity'
assert (BASE / 'run_routes.py').is_file(), 'Open this notebook in the extracted package folder.'
sys.path.insert(0, str(BASE))
from visualize_routes import prior_figure, screen_figures, pilot_figures, dashboard
OUT = BASE / 'outputs'
OUT.mkdir(exist_ok=True)
pio.renderers.default = 'plotly_mimetype'
print('LIVE AWS WORKFLOW — notebook 11; previous experiments are not rerun.')
print('Package:', BASE)

LIVE AWS WORKFLOW — notebook 11; previous experiments are not rerun.
Package: /home/sagemaker-user/kaggriculture_route_opportunity

### 1. What the preceding experiment established

The final-sale gate improved one primary development endpoint by 42 coins. The other two primary comparisons and all four negative controls were unchanged. No local match outcome changed. The report has no official submission score; two reused seed blocks and one related opponent do not establish generalization.

In [2]:
prior = json.loads((BASE / 'reference/notebook10_report.json').read_text())
review = json.loads((BASE / 'reference/input_review.json').read_text())
print('Returned bundle hashes verified:', review['bundle_files_verified'])
display(pd.DataFrame(prior['primary_results'])[['seed','seat','coins_control','coins_guarded','coins_delta','local_match_score_delta']])
figures = [prior_figure(BASE / 'reference')]
figures[0].show()

Returned bundle hashes verified: 27

,seed,seat,coins_control,coins_guarded,coins_delta,local_match_score_delta
0,1601,0,44840.0,44840.0,0.0,0.0
1,1601,1,44840.0,44840.0,0.0,0.0
2,1602,0,51764.0,51806.0,42.0,0.0

### 2. Registered comparison

The new route descriptor subtracts the best alternatives other friendly workers would lose if this route consumes their resources. It affects **menu admission only**. Each incumbent assignment route and direct deposit are protected, with eight non-PASS choices still allowed per worker. The same exact allocator and objective are used. A static tie keeps the old assignment.

Preserving the incumbent prevents a worse static objective, **not** a worse realized game outcome. The pilot therefore measures continuously advanced trajectories under a responsive opponent.

In [3]:
protocol = json.loads((BASE / 'PROTOCOL.json').read_text())
display(pd.DataFrame([{'screen_states':69, 'screen_cap_seconds':90,
    'pilot_cap_seconds':120, 'callback_cap_ms':500,
    'max_primary_pairs':1, 'max_negative_controls':1,
    'max_research_transitions':92, 'new_full_seasons':0,
    'non_PASS_menu_slots_per_worker':8}]))
print('Selection: first activated development source by seed/seat order, never by endpoint outcome.')

,screen_states,screen_cap_seconds,pilot_cap_seconds,callback_cap_ms,max_primary_pairs,max_negative_controls,max_research_transitions,new_full_seasons,non_PASS_menu_slots_per_worker
0,69,90,120,500,1,1,92,0,8

Selection: first activated development source by seed/seat order, never by endpoint outcome.

In [4]:
def run_stage(stage):
    emergency_seconds = {'screen':110, 'pilot':140}[stage]
    cmd = [sys.executable, str(BASE / 'run_routes.py'), stage]
    proc = subprocess.Popen(cmd, cwd=BASE, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, text=True, bufsize=1, start_new_session=True)
    started = time.monotonic()
    try:
        while proc.poll() is None:
            if time.monotonic() - started > emergency_seconds:
                raise TimeoutError('Notebook emergency deadline; bundle diagnostics.')
            ready, _, _ = select.select([proc.stdout], [], [], 1.0)
            if ready:
                line = proc.stdout.readline()
                if line: print(line, end='', flush=True)
        tail = proc.stdout.read()
        if tail: print(tail, end='')
        if proc.returncode:
            raise RuntimeError('Stage failed. Stop and use the bundle command; do not retry unchanged.')
    except BaseException:
        if proc.poll() is None:
            os.killpg(proc.pid, signal.SIGTERM)
            try: proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                os.killpg(proc.pid, signal.SIGKILL)
                proc.wait()
        raise

### 3. Stage A — observed-state feature activation

The screen verifies the real engine and source, compares every reconstructed original menu with the frozen menu, checks the full reference action, and measures candidate wall time. It writes a durable checkpoint after each of the three source episodes. If no first command changes, the next stage records a skipped pilot rather than running games.

In [5]:
run_stage('screen')

...........................................................RESULTS_BUNDLE: /tmp/tmpzikkn7h4/kaggriculture_route_opportunity_results.zip
.RESULTS_BUNDLE: /tmp/tmp_zmdgr4j/kaggriculture_route_opportunity_results.zip
...{"utc": "2026-09-12T00:46:07.620833+00:00", "stage": "VERIFIED_STAGE_REUSED", "name": "screen", "decision": "STOP_NO_ACTION_ACTIVATION"}
.....
----------------------------------------------------------------------
Ran 68 tests in 0.929s

OK
{"utc": "2026-09-12T00:46:08.715021+00:00", "stage": "PREFLIGHT_PASSED", "verified_objects": 10}
{"utc": "2026-09-12T00:46:10.696742+00:00", "stage": "SCREEN_EPISODE_SAVED", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "coordinated", "states": 23}
{"utc": "2026-09-12T00:46:12.749621+00:00", "stage": "SCREEN_EPISODE_SAVED", "seed": 1601, "seat": 1, "opponent": "livestock_fertilizer", "arm": "coordinated", "states": 23}
{"utc": "2026-09-12T00:46:14.945440+00:00", "stage": "SCREEN_EPISODE_SAVED", "seed": 1602, "seat": 0, "opponent": "livestock_fertilizer", "arm": "coordinated", "states": 23}
{"utc": "2026-09-12T00:46:15.767186+00:00", "stage": "ROUTE_OPPORTUNITY_SCREEN_COMPLETE", "decision": "ELIGIBLE_FOR_ONE_PAIRED_PILOT", "changed_states": 42}

In [6]:
screen = json.loads((OUT / 'screen/report.json').read_text())
print(screen['status'], screen['decision'])
display(pd.DataFrame([{k:screen[k] for k in ['observations','route_rows','numeric_descriptors_per_route',
    'changed_first_command_states','static_objective_improved_states','candidate_callback_max_ms','elapsed_seconds']}]))
print('Selected key:', screen['selected_key'])
screen_plots = screen_figures(OUT)
screen_plots[0].show()

ROUTE_OPPORTUNITY_SCREEN_COMPLETE ELIGIBLE_FOR_ONE_PAIRED_PILOT

,observations,route_rows,numeric_descriptors_per_route,changed_first_command_states,static_objective_improved_states,candidate_callback_max_ms,elapsed_seconds
0,69,19581,16,42,42,120.546204,8.961381

Selected key: {'arm': 'coordinated', 'opponent': 'livestock_fertilizer', 'seat': 0, 'seed': 1601}

In [7]:
screen_plots[1].show()
print('Static utility is not actual final cash. The incumbent feasible assignment was preserved.')

Static utility is not actual final cash. The incumbent feasible assignment was preserved.

In [8]:
screen_plots[2].show()
print('Opportunity cost here means alternatives lost by other workers on YOUR farm, not hidden opponent information.')

Opportunity cost here means alternatives lost by other workers on YOUR farm, not hidden opponent information.

In [9]:
screen_plots[3].show()
print('Activation is not feature importance. Seed/seat/step are audit metadata, not learned inputs.')

Activation is not feature importance. Seed/seat/step are audit metadata, not learned inputs.

In [10]:
screen_plots[4].show()
print('Local wall-clock measurements are not hosted Kaggle acceptance.')

Local wall-clock measurements are not hosted Kaggle acceptance.

### 4. Stage B — one primary pair after the no-change control

The same-state feature check gates the pilot. Both arms use notebook 10's final-sale rule. The control must reproduce the recorded earlier states and notebook 10's endpoint. The opponent recomputes its response each turn from its own observation. Candidate features cannot see the evaluator's other private view.

**No automatic expansion follows a win.** A null or negative result is preserved. An unresolved failure is not automatically retried.

In [11]:
run_stage('pilot')

{"utc": "2026-09-12T00:46:17.226067+00:00", "stage": "PREFLIGHT_PASSED", "verified_objects": 10}
{"utc": "2026-09-12T00:46:18.551147+00:00", "stage": "BRANCH_CHECKPOINT_SAVED", "mode": "control", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "sequential"}
{"utc": "2026-09-12T00:46:19.011367+00:00", "stage": "BRANCH_CHECKPOINT_SAVED", "mode": "opportunity", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "sequential"}
{"utc": "2026-09-12T00:46:19.017649+00:00", "stage": "PAIR_COMPLETE", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "sequential", "coins_delta": 0.0, "match_delta": 0.0}
{"utc": "2026-09-12T00:46:20.725752+00:00", "stage": "BRANCH_CHECKPOINT_SAVED", "mode": "control", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "coordinated"}
{"utc": "2026-09-12T00:46:21.517958+00:00", "stage": "BRANCH_CHECKPOINT_SAVED", "mode": "opportunity", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "coordinated"}
{"utc": "2026-09-12T00:46:21.524058+00:00", "stage": "PAIR_COMPLETE", "seed": 1601, "seat": 0, "opponent": "livestock_fertilizer", "arm": "coordinated", "coins_delta": -2.0, "match_delta": 0.0}
{"utc": "2026-09-12T00:46:21.533476+00:00", "stage": "ROUTE_OPPORTUNITY_PILOT_COMPLETE", "decision": "STOP_NEGATIVE_ENDPOINT"}

In [12]:
pilot = json.loads((OUT / 'pilot/report.json').read_text())
print(pilot['status'], pilot['decision'])
if pilot.get('completed_pairs'):
    display(pd.read_csv(OUT / 'pilot/paired_results.csv')[['seed','seat','role','coins_delta','coin_margin_delta',
        'local_match_score_delta','same_state_farm_changes']])
else:
    print('No pilot transitions: the feature family did not change a first action in the screen.')
pilot_plots = pilot_figures(OUT)
pilot_plots[0].show()

ROUTE_OPPORTUNITY_PILOT_COMPLETE STOP_NEGATIVE_ENDPOINT

,seed,seat,role,coins_delta,coin_margin_delta,local_match_score_delta,same_state_farm_changes
0,1601,0,negative_control,0.0,0.0,0.0,0
1,1601,0,primary,-2.0,1.0,0.0,9

In [13]:
pilot_plots[1].show()
print('A positive development pair is not independent validation or a leaderboard score.')

A positive development pair is not independent validation or a leaderboard score.

### 5. Save the evidence and stop compute

Save this notebook with **Ctrl+S**, then use the terminal command below to create the result ZIP. The bundle also works after an error. Download the result ZIP, then stop the `kaggriculture-dev` application in Studio. Do not delete the space.

Next research decisions follow the measured endpoint, not the quantity of candidate rows. Broad-workforce callback safety, full-season production/maintenance, hiring and land value, and independent opponent validation remain open.

In [14]:
dashboard(figures + screen_plots + pilot_plots, OUT / 'route_opportunity_dashboard.html')
print('NOTEBOOK11_COMPLETE:', pilot['decision'])
print('Save this notebook (Ctrl+S), then run:')
print(f'cd "{BASE}"')
print(f'"{sys.executable}" run_routes.py bundle')
print('Return kaggriculture_route_opportunity_results.zip — not the original input ZIP.')

NOTEBOOK11_COMPLETE: STOP_NEGATIVE_ENDPOINT
Save this notebook (Ctrl+S), then run:
cd "/home/sagemaker-user/kaggriculture_route_opportunity"
"/home/sagemaker-user/projects/kaggriculture/.venv/bin/python" run_routes.py bundle
Return kaggriculture_route_opportunity_results.zip — not the original input ZIP.